apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort # Exposes the service on the node's IP
  selector:
    app: backend # Routes traffic to any Pod with the label "app: backend"
  ports:
  - port: 80      # The service's internal port
    targetPort: 8000 # The port on the container (our app)
    nodePort: 30007  # The static port to expose on the "node"